# Generated by Django 3.2.14 on 2022-07-07 12:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.TextField(max_length=8000)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_ip', models.GenericIPAddressField()),
                ('event_question', models.CharField(max_length=1000)),
                ('event_answer', models.CharField(max_length=2000)),
                ('user_datetime', models.DateTimeField(auto_now_add=True)),
                ('intent', models.CharField(default='', max_length=100)),
                ('event_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zayed_university_app.eventtype')),
            ],
            options={
                'db_table': 'zayed_university_app_log',
            },
        ),
    ]
